[platformio]
src_dir = Reward_Dispenser_v2

[env:esp32c3]
platform   = espressif32
board      = esp32-c3-devkitm-1
framework  = arduino
monitor_speed = 115200

lib_deps =
  bblanchon/ArduinoJson @ ^7.0.0
  adafruit/Adafruit NeoPixel @ ^1.0.0
  stan-reifel/SpeedyStepper @ ^1.0.0