name: Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install PlatformIO
        run: pip install platformio

      - name: Compile
        run: platformio run

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: .pio/build/esp32c3/firmware.bin